{
  "formatVersion": "1.1",
  "component": {
    "group": "solomonoff",
    "module": "solomonoff",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "7vdpx5je5nh5xmtnsbxuztrf54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "net.automatalib.distribution",
          "module": "automata-distribution",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "de.learnlib.distribution",
          "module": "learnlib-distribution",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "solomonoff-1.3.jar",
          "url": "solomonoff-1.3.jar",
          "size": 160654,
          "sha512": "b66acd702f12b3470239603cd68d6f898674a555b568f4572571965003dbfda1b083ec4988dee3a861e8231e98a31750ff42866ea86d71e179570a5d8be2ae66",
          "sha256": "8e80523f67ec7b3aa94f17d2dedb876ba3d6b045813500ba8fef5eb040d411bb",
          "sha1": "71db2339841e50e70255fe59d044efe3a301c79a",
          "md5": "48bf19657dbf2f68d88cc12b0301e3df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "net.automatalib.distribution",
          "module": "automata-distribution",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "de.learnlib.distribution",
          "module": "learnlib-distribution",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "solomonoff-1.3.jar",
          "url": "solomonoff-1.3.jar",
          "size": 160654,
          "sha512": "b66acd702f12b3470239603cd68d6f898674a555b568f4572571965003dbfda1b083ec4988dee3a861e8231e98a31750ff42866ea86d71e179570a5d8be2ae66",
          "sha256": "8e80523f67ec7b3aa94f17d2dedb876ba3d6b045813500ba8fef5eb040d411bb",
          "sha1": "71db2339841e50e70255fe59d044efe3a301c79a",
          "md5": "48bf19657dbf2f68d88cc12b0301e3df"
        }
      ]
    }
  ]
}
