version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./compile_repl.sh
      - run: ./repl_unit_tests.sh
      - run: ./repl_integration_tests.sh

workflows:
  maven_test:
    jobs:
      - build

